/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package xpath.belowwaterapp;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author niamh
 */
public class VeiwGUI extends javax.swing.JFrame {

    private ArrayList <Fish> fishes;
    
    /**
     * Creates new form VeiwGUI
     */
    public VeiwGUI() {
        initComponents();
        typeCBX.setVisible(false);
        typeLBL.setVisible(false);
        soldLBL.setVisible(false);
        soldTF.setVisible(false);
        caughtLBL.setVisible(false);
        caughtTF.setVisible(false);
        addBTN.setVisible(false);
        fishes = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        titleLBL = new javax.swing.JLabel();
        coOrdLB = new javax.swing.JLabel();
        overTF = new javax.swing.JTextField();
        downTF = new javax.swing.JTextField();
        goBTN = new javax.swing.JButton();
        addFishBTN = new javax.swing.JButton();
        typeCBX = new javax.swing.JComboBox<>();
        caughtLBL = new javax.swing.JLabel();
        soldLBL = new javax.swing.JLabel();
        typeLBL = new javax.swing.JLabel();
        caughtTF = new javax.swing.JTextField();
        soldTF = new javax.swing.JTextField();
        addBTN = new javax.swing.JButton();
        returnBTN = new javax.swing.JButton();
        bgLBL = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1000, 1000));
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        titleLBL.setFont(new java.awt.Font("Comic Sans MS", 0, 48)); // NOI18N
        titleLBL.setText("Go Fishing");
        getContentPane().add(titleLBL);
        titleLBL.setBounds(177, 0, 243, 63);

        coOrdLB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        coOrdLB.setText("Co Ordinates (X,Y) : ");
        getContentPane().add(coOrdLB);
        coOrdLB.setBounds(6, 69, 130, 20);

        overTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overTFActionPerformed(evt);
            }
        });
        getContentPane().add(overTF);
        overTF.setBounds(6, 95, 45, 22);

        downTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downTFActionPerformed(evt);
            }
        });
        getContentPane().add(downTF);
        downTF.setBounds(57, 95, 48, 22);

        goBTN.setBackground(new java.awt.Color(153, 255, 204));
        goBTN.setToolTipText("");
        goBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBTNActionPerformed(evt);
            }
        });
        getContentPane().add(goBTN);
        goBTN.setBounds(111, 101, 20, 16);

        addFishBTN.setBackground(new java.awt.Color(102, 204, 255));
        addFishBTN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addFishBTN.setText("Add Fish Data");
        addFishBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFishBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addFishBTN);
        addFishBTN.setBounds(6, 135, 125, 34);

        typeCBX.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "Mackerel", "Pollack", "Codling", "Whiting" }));
        typeCBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeCBXActionPerformed(evt);
            }
        });
        getContentPane().add(typeCBX);
        typeCBX.setBounds(79, 204, 81, 22);

        caughtLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        caughtLBL.setText("Caught:");
        getContentPane().add(caughtLBL);
        caughtLBL.setBounds(4, 241, 60, 16);

        soldLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        soldLBL.setText("Sold:");
        getContentPane().add(soldLBL);
        soldLBL.setBounds(2, 269, 50, 16);

        typeLBL.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        typeLBL.setText("Species: ");
        typeLBL.setToolTipText("");
        getContentPane().add(typeLBL);
        typeLBL.setBounds(7, 207, 60, 16);

        caughtTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caughtTFActionPerformed(evt);
            }
        });
        getContentPane().add(caughtTF);
        caughtTF.setBounds(81, 238, 71, 22);

        soldTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                soldTFActionPerformed(evt);
            }
        });
        getContentPane().add(soldTF);
        soldTF.setBounds(81, 266, 71, 22);

        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN);
        addBTN.setBounds(50, 300, 60, 23);

        returnBTN.setText("Return to Home");
        returnBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBTNActionPerformed(evt);
            }
        });
        getContentPane().add(returnBTN);
        returnBTN.setBounds(655, 10, 160, 40);

        bgLBL.setIcon(new javax.swing.ImageIcon("C:\\Users\\niamh\\Downloads\\fishingBG.png")); // NOI18N
        getContentPane().add(bgLBL);
        bgLBL.setBounds(0, 0, 860, 730);

        pack();
    }// </editor-fold>                        

    private void overTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void downTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void goBTNActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
        CoOrdinates c = new CoOrdinates();
        c.setOver(Integer.parseInt(overTF.getText()));
        c.setDown(Integer.parseInt(downTF.getText()));
        
    }                                     

    private void typeCBXActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void caughtTFActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void soldTFActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void addFishBTNActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
        typeCBX.setVisible(true);
        typeLBL.setVisible(true);
        soldLBL.setVisible(true);
        soldTF.setVisible(true);
        caughtLBL.setVisible(true);
        caughtTF.setVisible(true);
        addBTN.setVisible(true);
    }                                          

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        //Fish f = new Fish();
        //int type = typeCBX.getSelectedIndex();
        //f.setType(type);
        //f.setCaught(Integer.parseInt(caughtTF.getText()));
        //f.setSold(Integer.parseInt(soldTF.getText()));
        //fishes.add(f);
    }                                      

    private void returnBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        HomeGUI myWaterGUI = new HomeGUI();
        myWaterGUI.setVisible(true);
        
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VeiwGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VeiwGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VeiwGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VeiwGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VeiwGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBTN;
    private javax.swing.JButton addFishBTN;
    private javax.swing.JLabel bgLBL;
    private javax.swing.JLabel caughtLBL;
    private javax.swing.JTextField caughtTF;
    private javax.swing.JLabel coOrdLB;
    private javax.swing.JTextField downTF;
    private javax.swing.JButton goBTN;
    private javax.swing.JButton jButton1;
    private javax.swing.JTextField overTF;
    private javax.swing.JButton returnBTN;
    private javax.swing.JLabel soldLBL;
    private javax.swing.JTextField soldTF;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JComboBox<String> typeCBX;
    private javax.swing.JLabel typeLBL;
    // End of variables declaration                   
}
